import org.opencv.core.*;
import org.opencv.highgui.Highgui;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.imgproc.Imgproc;
import org.opencv.videoio.VideoCapture;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.InputStream;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    static boolean running = true;

    static {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
    }

    public static void main(String[] args) {
        System.out.println("Welcome to OpenCV " + Core.VERSION);
        Mat m = new Mat(5, 10, CvType.CV_8UC1, new Scalar(0));
        System.out.println("OpenCV Mat: " + m);
        Mat mr1 = m.row(1);
        mr1.setTo(new Scalar(1));
        Mat mc5 = m.col(5);
        mc5.setTo(new Scalar(5));
        System.out.println("OpenCV Mat data:\n" + m.dump());

        JFrame frame = new JFrame("TestJFrame");
        ImagePanel panel = new ImagePanel();
        frame.add(panel);
        frame.setVisible(true);
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        VideoCapture capt = new VideoCapture();
        System.out.println("Opening Capture");
        capt.open(0);
        System.out.println("Opened Capture");

        frame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                running = false;
            }
        });

        Mat currImg = new Mat();
        Mat oldImg = new Mat();
        Mat actImg = new Mat();

        capt.read(oldImg);
        frame.setSize(oldImg.width(),oldImg.height());
        panel.setImage(oldImg);

        while(running){
            capt.read(currImg);
            Core.subtract(currImg, oldImg, actImg);
            oldImg = currImg.clone();
            panel.setImage(actImg);
        }

        capt.release();
    }
}
