name: RobolabStatisticsEnv
channels:
  - conda-forge
  - pypi
  - pytorch
dependencies:
  - python=3.6
  - numpy=1.14.0
  - opencv=3.3.0
  - keras=2.1.5
  - keras-gpu=2.1.5
  - tensorflow=1.7.0
  - tensorflow-gpu=1.7.0
  - tensorboard=1.7.0
  - matplotlib=2.1.1
  - scikit-learn=0.19.1
  - dropbox=8.5.0
  - pip:
    - pymunk
    - pygame

