name: RobolabStatisticsEnv
channels:
  - conda-forge
  - pypi
dependencies:
  - python=3.6
  - numpy=1.14.0
  - opencv=3.3.0
  - keras=2.0.9
  - tensorflow=1.4.0
  - tensorflow-tensorboard=0.4.0
  - matplotlib=2.1.1
  - pip:
    - pymunk

