import org.opencv.core.*;
import org.opencv.videoio.VideoCapture;
import robogui.RoboGui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    static boolean running = true;

    static {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
    }

    public static void main(String[] args) {
        System.out.println("Welcome to OpenCV " + Core.VERSION);
        Mat m = new Mat(5, 10, CvType.CV_8UC1, new Scalar(0));
        System.out.println("OpenCV Mat: " + m);
        Mat mr1 = m.row(1);
        mr1.setTo(new Scalar(1));
        Mat mc5 = m.col(5);
        mc5.setTo(new Scalar(5));
        System.out.println("OpenCV Mat data:\n" + m.dump());

        VideoCapture capt = new VideoCapture();
        System.out.println("Opening Capture");
        capt.open(0);
        System.out.println("Opened Capture");

        RoboGui.getInstance().addWindowListener("NormalFrame", new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                running = false;
            }
        });
        RoboGui.getInstance().addWindowListener("MotionFrame", new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                running = false;
            }
        });

        Mat currImg = new Mat();
        Mat oldImg = new Mat();
        Mat actImg = new Mat();

        capt.read(oldImg);
        RoboGui.getInstance().setFrameSize("NormalFrame", oldImg.width(), oldImg.height());
        RoboGui.getInstance().setFrameSize("MotionFrame", oldImg.width(), oldImg.height());


        while(running){
            capt.read(currImg);
            Core.subtract(currImg, oldImg, actImg);
            oldImg = currImg.clone();
            RoboGui.getInstance().show("NormalFrame", currImg);
            RoboGui.getInstance().show("MotionFrame", actImg);
        }

        capt.release();
        RoboGui.getInstance().close();
    }
}
